# Generated by Django 5.1.4 on 2024-12-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registrar_usuarios_delete_user_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Registrar_usuarios',
        ),
    ]
