# Generated by Django 5.1.4 on 2024-12-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_register_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_register',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
